### ISSUE TITLE
Unable to load clean-css (Ubuntu 17.10)

### ISSUE THREAD

**Issue by Arahort** [less/less-plugin-clean-css#24] opened 2018-03-18 15:12 UTC
Hello everybody! I have a problem that I hope you will help to solve:
PhpStorm 2017.2(Win 10) + Node.js install
Terminal install less and plugin

> X:\PhpstormProjects\xxx>npm install -g less
> C:\Users\xxx\AppData\Roaming\npm\lessc -> C:\Users\xxx\AppData\Roaming\npm\node_modules\less\bin\lessc
> + less@3.0.1
> updated 1 package in 4.055s
> 
> X:\PhpstormProjects\xxx>npm install -g less-plugin-clean-css
> + less-plugin-clean-css@1.5.1
> updated 1 package in 1.068s

Add less watcher, all work fine, less compiles, but
If i want use plugin i add in watcher arguments --clean-css="--s1 --advanced --compatibility=ie8" (tried many different options)
Next, I make changes to my .less file and take

> cmd.exe /D /C call C:/Users/XXX/AppData/Roaming/npm/lessc.cmd --no-color main.less "--clean-css=--s1 --advanced --compatibility=ie8"
> Unable to load plugin clean-css please make sure that it is installed under or at the same level as less
> 
> Process finished with exit code 1

**Comment by seven-phases-max** [comment] 2018-03-18 15:32
first I thought it's th same as https://github.com/less/less-plugin-clean-css/issues/23 but in your case it ooks different. Either way try to downgrade to latest `less 2.x`.

**Comment by matthew-dean** [comment] 2018-03-19 17:32
> Either way try to downgrade to latest less 2.x.

😢

**Comment by powerriegel** [comment] 2018-04-16 14:16
No PHP Storm Problem. It's an Ubuntu 17.10 problem. 
```
/usr/local/lib
└── less-plugin-clean-css@1.5.1
lessc 3.0.1 (Less Compiler) [JavaScript]
```

Lessc is totally broken in 17.10. Neither clean-css nor source mape work.

**Comment by matthew-dean** [comment] 2018-04-25 16:07
Is this solved by https://github.com/less/less.js/pull/3200 ?

**Comment by Arahort** [comment] 2018-05-10 15:14
You incorrectly changed the title, in the first message I wrote that the problem is also observed in Win10

**Comment by seven-phases-max** [comment] 2018-05-14 12:35
@Arahort OK, than it simply a duplicate of #23.

**Comment by seven-phases-max** [comment] 2018-05-14 12:36
Closing as a duplicate of #23.

**Closed by seven-phases-max** 2018-05-14 12:36 UTC
Labels: needs research
